apiVersion: v1     #string

kind: Pod          #string

metadata:           #dictionary
  name: myapp-pod   
  namespace: <namespace-name>
  labels:            
    app: myapp      
    type: front-end

spec:              #dictionary
  containers:      #list/array 
    - name: nginx-controller    # "-" for name specifies that it is the first item in the list.
      image: nginx
  
  nodeName: node02    # Manual Scheduling
  
  tolerations:          # tolerations - this pod will only place on the app=blue taint node
    - key: "app"
      operator: "Equal"
      value: "blue"
      effect: "NoSchedule"
  
  nodeSelector:      # Node Selector - k8s will only place this pod on node which has label as "size=Large"
    size: Large

  resources:        # Resources Requests - By default, K8s allocates a pod 0.5 cpu and 256Mi of memory, to allocate more resources, use resource requests
    requests:
      memory: "1Gi"
      cpu: 1
      
  schedulerName: my-customer-scheduler    # Custom scheduler created by us, can be specify like this.
