apiVersion: v1

kind: ReplicationController

metadata:
  name: myyapp-rep-contr
  labels: 
    tier: frontend
    app: myapp
    
spec:
  replicas: 5
  template:
    metadata:
      name: my-app-pod
      labels:
        app: front-end-pod
        tier: frontend
    spec:
      containers:
        - name: myapp-nginx
          image: nginx
