apiVersion: v1
kind: Service
metadata: 
  name: my-nodeport-service
  labels:
    tier: frontend
spec:
  type: NodePort
  ports:
   - targetPort: 80
     port: 80
     NodePort: 30008
  selector:                   # pod labels
    matchLabels:
      app: myapp
      type: front-end
     
