apiVersion: v1

kind: Service

metadata:
  name: jenkins-service
  labels:
    name: jenkins-service
    type: jenkins-service

spec:
  type: NodePort
  ports:
    - targetPort: 8080
      port: 8080
      nodePort: 30008

  selector:
    name: jenkins-pod
    type: jenkins-pod