apiVersion: v1

kind: Service

metadata:
  name: back-end

spec:
  type: ClusterIP
  ports:
    - targetPort: 80  #backend actual port
      port: 80        #clusterip service port
      nodePort: 30008

#link to the backend
  selector:
    app: myapp
    type: back-end