apiVersion: v1
kind: Pod
metadata:
  name: result-pod
  labels:
    name: result-pod
    app: demo-voting-app

spec:
  containers:
    - name: result
      image: dockersamples/exampleresultapp_worker
      ports:
        - containerPort: 80
